feat: Implement product checkout
Fitted-NG/landing-pages pull request #99
Opened 2024-01-19 10:39 UTC by TPriince

1. Created checkout workflow - to collect user details (address details included)
2. Implemented editing of user details in the order confirmation segment
3. Integrated Paystack

2024-01-19 20:12 UTC, blissuche90 commented on src/app/magic/checkout/[productId]/page.tsx
> +  const res = await getAllProducts(params.productId);
All this looks like Js, no strong typing.

2024-01-19 20:14 UTC, blissuche90 commented on src/components/magic/checkout/sendPayment.ts
> +    const res = await fetch(url, {
I think we should have a central function for sending out request that should be used across the entire project.

2024-01-19 20:15 UTC, blissuche90 requested changes
Please fix comments

2024-01-20 13:01 UTC, TPriince commented
They have all been attended to. I will close this PR and make a new one with the updates. @blissuche90

2024-01-20 13:06 UTC, closed without merging